name: CI — Docker Build & Smoke

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch optional)
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: local/test:ci

      - name: Smoke test (container starts)
        run: |
          docker run -d --rm --name app local/test:ci || exit 1
          sleep 8
          docker ps | grep app
          docker logs app --tail=100 || true
          docker rm -f app || true
